name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    # skip this job for PRs from forks (only run for PRs coming from this repo or for non-PR events)
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: SonarQube Scan
        # only run Sonar step if the secret exists
        
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # optionally:
          # SONAR_HOST_URL: https://sonarcloud.io
