name: OWASP ZAP Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run ZAP Full Scan
        run: |
          docker run -v ${{ github.workspace }}:/zap/wrk/:rw -t owasp/zap2docker-stable \
          zap-full-scan.py -t http://host.docker.internal:5173 \
          -c zap.yaml -r /zap/wrk/zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Report
          path: zap_report.html


